<template>
  <div class="join-view">
    <n-card class="join-card">
      <h2 class="title">加入房间 {{ roomId }}</h2>
      <div v-if="hasPlayerName" class="loading-text">
        <n-spin size="small" />
        <p>正在使用昵称 <strong>{{ playerName }}</strong> 加入房间...</p>
      </div>
      <n-space v-else vertical size="large">
        <n-alert v-if="autoGeneratedName" title="自动分配昵称" type="info" :show-icon="false">
          已为您自动分配昵称 <strong>{{ newPlayerName }}</strong>，您可以修改或直接使用。
        </n-alert>
        <p>请输入你的昵称以加入游戏：</p>
        <n-input v-model:value="newPlayerName" placeholder="请输入你的昵称" size="large" @keyup.enter="handleJoinRoom" />
        <n-button type="primary" size="large" block @click="handleJoinRoom" :disabled="!newPlayerName">
          确认加入
        </n-button>
      </n-space>
    </n-card>
  </div>
</template>

<script setup>
import { ref, onMounted, computed } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useGameStore } from '@/store/game';
import { NCard, NInput, NButton, NSpace, NSpin, NAlert } from 'naive-ui';

const route = useRoute();
const router = useRouter();
const game = useGameStore();

const roomId = ref(route.params.roomId);
const playerName = ref(localStorage.getItem('playerName') || '');
const newPlayerName = ref('');
const autoGeneratedName = ref(false);
const hasPlayerName = computed(() => !!playerName.value);

// 生成随机昵称
const generateRandomName = () => {
  const adjectives = ['快乐的', '聪明的', '勇敢的', '可爱的', '机智的', '友好的', '活泼的', '温暖的', '有趣的', '神秘的'];
  const nouns = ['玩家', '战士', '冒险者', '英雄', '小精灵', '魔法师', '骑士', '守护者', '探索者', '旅行者'];
  const randomNum = Math.floor(Math.random() * 1000);
  
  const adjective = adjectives[Math.floor(Math.random() * adjectives.length)];
  const noun = nouns[Math.floor(Math.random() * nouns.length)];
  
  return `${adjective}${noun}${randomNum}`;
};

const handleJoinRoom = () => {
  const nameToJoin = playerName.value || newPlayerName.value;
  if (!nameToJoin) return;

  localStorage.setItem('playerName', nameToJoin);
  // 设置标记，表示这是新加入的用户
  sessionStorage.setItem('isNewUser', 'true');
  game.socket.joinRoom({
    roomId: roomId.value,
    playerName: nameToJoin,
  });
  // 之后由 socket 的 onRoomJoined 事件来处理跳转
};

onMounted(() => {
  if (hasPlayerName.value) {
    handleJoinRoom();
  } else {
    // 如果没有保存的用户名，自动生成一个
    newPlayerName.value = generateRandomName();
    autoGeneratedName.value = true;
  }
});
</script>

<style scoped>
.join-view {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  background: linear-gradient(135deg, #f8fafc 0%, #e0e5ec 100%);
}
.join-card {
  width: 100%;
  max-width: 400px;
  padding: 24px;
  border-radius: 12px;
}
.title {
  text-align: center;
  margin-bottom: 24px;
}
.loading-text {
  text-align: center;
  padding: 20px 0;
}
</style> 